# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LUN7XKmW6bsbrA-sdREMaU851owCqrgf
"""


from flask import Flask, render_template

with open("test.html", "w", encoding="utf-8") as f:
    f.write("""<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>てすとだよ〜</title>
</head>
<body>
    <h1>てすてぃんぐ!</h1>
</body>
</html>
  """)

# Flaskアプリの作成
app = Flask(__name__)
## 送信画面のルーティング
@app.route('/')
def index():
     return render_template('test.html')

